import React from "react";
import type { Metadata } from "next";
import { Libre_Franklin } from "next/font/google";
import { ModalProvider } from "@/context/modalContext";
import Header from "@/components/header";
import "./globals.css";

const libreFranklin = Libre_Franklin({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Diciopen | Defina o seu mundo",
  description: "Generated by Diciopen | Defina o seu mundo",
  themeColor: "#008000",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={libreFranklin.className}>
        <ModalProvider>
          <Header />
          {children}
        </ModalProvider>
      </body>
    </html>
  );
}
